### ISSUE TITLE
css is not loaded

### ISSUE THREAD

**Issue by FerdinandFidel** [vestusola/vue-chat-emoji#26]
I use the following two line to load the resources in a vue-component:

```
import { VueChatEmoji, emojis } from 'vue-chat-emoji
require("vue-chat-emoji/dist/vue-chat-emoji.css");
```

Then i get this error message:

` vue-chat-emoji/dist/vue-chat-emoji.css in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/group.vue?vue&type=script&lang=js&
`

If I try it globally with these code lines:

```
import { VueChatEmoji } from 'vue-chat-emoji';
Vue.component("Emoji", VueChatEmoji);
require("vue-chat-emoji/dist/vue-chat-emoji.min.css");

Vue.config.productionTip = false;
Vue.use(Emoji);
```

Then i get this error message:

`ESLint: 'Emoji' is not defined.(no-undef)`

Does anyone know a solution? 
I only need this function: emojis.decodeEmoji(str).

Many greetings

**Comment by vestusola** [comment]
Hi @FerdinandFidel ,
You can use the emojis property in your component through import.
```js
<script>
import { emojis } from 'vue-chat-emoji';
export default {
   mounted() {
      console.log(emojis.decodeEmoji(':birthday_cake:'));
   }
}
</script>
```
Just like the above.

Thanks and best wishes!

**Comment by vestusola** [comment]
Incase you want to use global install in your main.js or app.js
```js
<script>
/* eslint-disable no-undef */
import Vue from "vue";

import { VueChatEmoji } from 'vue-chat-emoji';
Vue.component("Emoji", VueChatEmoji);
require('vue-chat-emoji/dist/vue-chat-emoji.min.css');
</script>
```

Then on your component, you can use this
```js
<script>
import { VueChatEmoji, emojis } from "vue-chat-emoji";
export default {
  components: {
     YourLocalComponentName: VueChatEmoji
  },
   mounted() {
      console.log(emojis.decodeEmoji(':birthday_cake:'));
   }
}
</script>
```

**Comment by vestusola** [comment]
> Incase you want to use global install in your main.js or app.js
> 
> ```js
> <script>
> /* eslint-disable no-undef */
> import Vue from "vue";
> 
> import { VueChatEmoji } from 'vue-chat-emoji';
> Vue.component("Emoji", VueChatEmoji);
> require('vue-chat-emoji/dist/vue-chat-emoji.min.css');
> </script>
> ```
> 
> Then on your component, you can use this
> 
> ```js
> <script>
> import { VueChatEmoji, emojis } from "vue-chat-emoji";
> export default {
>   components: {
>      YourLocalComponentName: VueChatEmoji
>   },
>    mounted() {
>       console.log(emojis.decodeEmoji(':birthday_cake:'));
>    }
> }
> </script>
> ```

Remember to add font-awesome as a node module or add cdn link within component
<style lang="scss">
@import 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css';
</style>

**Comment by FerdinandFidel** [comment]
> Hi @FerdinandFidel , You can use the emojis property in your component through import.
> 
> ```js
> <script>
> import { emojis } from 'vue-chat-emoji';
> export default {
>    mounted() {
>       console.log(emojis.decodeEmoji(':birthday_cake:'));
>    }
> }
> </script>
> ```
> 
> Just like the above.
> 
> Thanks and best wishes!

Thx, that works. But there are problems with the naming. In our app it is called 'white_check_mark', but here it is 'check_mark_button'. Maybe there are more differences.

**Comment by vestusola** [comment]
> > Hi @FerdinandFidel , You can use the emojis property in your component through import.
> > ```js
> > <script>
> > import { emojis } from 'vue-chat-emoji';
> > export default {
> >    mounted() {
> >       console.log(emojis.decodeEmoji(':birthday_cake:'));
> >    }
> > }
> > </script>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Just like the above.
> > Thanks and best wishes!
> 
> Thx, that works. But there are problems with the naming. In our app it is called 'white_check_mark', but here it is 'check_mark_button'. Maybe there are more differences.

You can use emojis.encodeEmoji('✅') to get the key code, which you can use in your app.

**Comment by vestusola** [comment]
Since it is open-source, you can edit and adjust for your use.

**Comment by FerdinandFidel** [comment]
I thought there were standards, but there are differences. Thx.
