### ISSUE TITLE
emmmmmm

### ISSUE THREAD

**Issue by a1392558812** [vestusola/vue-chat-emoji#5]
well,i want to set 'width' or 'height' ,how should i do?

**Comment by vestusola** [comment]
Sorry about that. Will push a new update very soon.

**Comment by a1392558812** [comment]
up ,How can I use this tool through a CDN path instead of using NPM

**Comment by vestusola** [comment]
I will push the update tomorrow. And will also walk you through using CDN instead of NPM

**Comment by a1392558812** [comment]
> I will push the update tomorrow. And will also walk you through using CDN instead of NPM

Thanks, up. You're an angel

**Comment by vestusola** [comment]
> > I will push the update tomorrow. And will also walk you through using CDN instead of NPM
> 
> Thanks, up. You're an angel

😀. You can pull the latest update version 1.1.26 and read the README.md

**Comment by a1392558812** [comment]
> > > I will push the update tomorrow. And will also walk you through using CDN instead of NPM
> > 
> > 
> > Thanks, up. You're an angel
> 
> 😀. You can pull the latest update version 1.1.26 and read the README.md

😀😀😀😀Thank you very much. you've been most helpful.

**Comment by vestusola** [comment]
> > > > I will push the update tomorrow. And will also walk you through using CDN instead of NPM
> > > 
> > > 
> > > Thanks, up. You're an angel
> > 
> > 
> > 😀. You can pull the latest update version 1.1.26 and read the README.md
> 
> 😀😀😀😀Thank you very much. you've been most helpful.

Glad I can be of help.
